### ISSUE TITLE
FIX: Items search

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/backend#43]
On the frontend, we got issues with item filtering on /items page with a big amount of items. 
It is super slow :D We are currently doing all the filtering on the frontend, and testing this using data@test.com account, which has 571 items, showed that some queries can take around 2 seconds (especially single-letter ones) which seems a lot for 500 items. This was tested on a MacBook Pro, I haven't tested it on a 'regular' computer.
Should we handle filtering on the server-side instead of the client-side?
We should test this, to see what the differences are.

**Comment by ips-coding-challenge** [comment]
In this use case, I'm not sure that's a good idea. If we do the search on the backend we'll have to debounce the input, so, first of all, we should try to debounce the input on the front-end to see the result. Also, with a slow internet connection, we will have a worse user experience. I will first try to see what I can do in the front-end. There are also libraries like Fuse.js which create indexes to make the search faster but I don't know if it corresponds to our use case yet ;).

If nothing works, I will take a look to do it in the backend ;)
